-- Generated by build_report_sql_with_instructor.py
BEGIN;

INSERT INTO public.universes (code, name, description, cover_image_url, is_active)
VALUES
  ('NLA-U-89', '星骸深渊', '一个没有恒星与行星的宇宙，唯有无垠的高浓度以太之海，以及漂浮其中、体型堪比星系的“太古星兽”尸骸。所有的文明都寄生在这些不可名状的巨物骨骼与腐肉之中，以开采它们残存的生物质能（神髓）为生。', NULL, true),
  ('NLA-U-104', '暮血圣座', '一个被永恒的黄昏阴霾笼罩、理性濒临全面崩溃的世界。物理法则屈从于精神的异化，宏伟的哥特式城邦建立在不断腐坏与增生的活体有机物之上。狂热的信仰机器与禁忌的血肉炼金术在此展开无休止的残酷绞杀。', NULL, true)
ON CONFLICT (code) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cover_image_url = EXCLUDED.cover_image_url,
  is_active = EXCLUDED.is_active,
  updated_at = now();

WITH seed AS (
  SELECT *
  FROM (
    VALUES
  ('NLA89-DECAY-PULSE-CROSSBOW', 'NLA-U-89', 65000, true),
  ('NLA89-ECHOLIA-BOLTER', 'NLA-U-89', 55000, true),
  ('NLA89-OSTEO-DISSOLVER-SPOUT', 'NLA-U-89', 50000, true),
  ('NLA89-PREDATOR-CHAIN-SWORD', 'NLA-U-89', 50000, true),
  ('NLA89-SEISMIC-OSSIFIED-SLEDGE', 'NLA-U-89', 65000, true),
  ('NLA104-SAINTS-RIB-SCYTHE', 'NLA-U-104', 60000, true),
  ('NLA104-INQUISITOR-PIERCER', 'NLA-U-104', 60000, true),
  ('NLA104-EMBER-BLOOD-BLUNDERBUSS', 'NLA-U-104', 50000, true),
  ('NLA104-BOILING-BLOOD-NAILER', 'NLA-U-104', 55000, true),
  ('NLA104-THORN-SANGUINE-PUMP', 'NLA-U-104', 55000, true),
  ('NLA104-SLUMBERING-ICHOR-GRENADE', 'NLA-U-104', 65000, true)
  ) AS v(sku_code, universe_code, list_price_qc, is_active)
),
resolved AS (
  SELECT s.sku_code, u.id AS native_universe_id, s.list_price_qc, s.is_active
  FROM seed s
  JOIN public.universes u ON u.code = s.universe_code
)
INSERT INTO public.weapons (sku_code, native_universe_id, list_price_qc, is_active)
SELECT sku_code, native_universe_id, list_price_qc, is_active
FROM resolved
ON CONFLICT (sku_code) DO UPDATE
SET
  native_universe_id = EXCLUDED.native_universe_id,
  list_price_qc = EXCLUDED.list_price_qc,
  is_active = EXCLUDED.is_active,
  updated_at = now();

WITH seed AS (
  SELECT *
  FROM (
    VALUES
  ('NLA89-DECAY-PULSE-CROSSBOW', '“寂灭脉冲”脊椎弩', '一种利用生物机械张力发射动能弹药的中远距离武器。其结构模拟大型星兽的脊椎连接方式，通过外部泵入的神髓激活内部神经节，产生瞬间超高强度的肌肉纤维收缩，驱动弩机。', '全长 1.2m - 1.5m，展开宽度 0.8m，单兵持握重量约 12kg。', '脱水处理的星兽脊椎骨骼、高张力干缩肌肉纤维、活性神经节。', '需定期补充提纯“神髓”能源液；弹药为特制的钙化骨刺。', '物理张力做功。骨刺弹头涂层在撞击时诱发神髓微型裂变，通过次声波震荡破坏目标的生命维持系统。', NULL, NULL, '在无金属环境下，利用生物组织的高抗拉强度实现超越常规火药驱动的初速。'),
  ('NLA89-ECHOLIA-BOLTER', '“回声”连发髓枪', '基于流体力学原理的半自动生物射击武器，利用生物节律实现连续激发。', '长度约 0.45m，手枪式握持结构，紧凑型体积。', '中空星兽指骨、柔性括约肌组织、痛觉感应中枢。', '使用者需通过握压痛觉感受器与武器建立生物反馈，消耗临界态液态神髓。', '液压推动。通过诱导内部括约肌群产生节律性收缩，将神髓结晶碎片以高速喷射流形式排出。', NULL, '运作过程中会产生极高分贝的生物声频，长期使用会导致听力受损。', '必须保持内部神髓处于临界高压态，否则无法维持连发压强。'),
  ('NLA89-OSTEO-DISSOLVER-SPOUT', '“溶骨者”胃酸喷雾器', '一种化学腐蚀性单兵喷射装置，用于阵地清场与破坏生物质装甲。', '背负式培养囊（体积约 20L），连接 1.2m 柔性导管。', '生物培养囊肿、多层几丁质调节板、柔性食道组织。', '依赖背负式囊肿实时合成浓缩胃酸；需手动调节几丁质挡板以切换喷射模式。', '化学强力氧化与溶解。通过气压差将极端强酸喷向目标，针对几丁质与钙化装甲有极强腐蚀效力。', NULL, NULL, '喷管内壁必须具备生物抗酸性涂层，严禁在狭小密闭空间且无防护状态下使用。'),
  ('NLA89-PREDATOR-CHAIN-SWORD', '“捕食者”活性链锯剑', '将活性寄生生物与冷兵器结合的近战武器。利用生物振动频率增加切割效能。', '全长 1.1m，重约 7kg。', '钙化剑刃基座、“蚀骨虫”寄生群体、神髓循环回路。', '需要稳定的神髓循环供能以维持寄生虫活性。', '高频振动切割。神髓刺激“蚀骨虫”产生万赫兹级别的振动，并伴随生物啃噬效应破坏目标微观结构。', NULL, '一旦神髓供应中断，内部寄生虫将由于饥饿转而攻击持有者。', NULL),
  ('NLA89-SEISMIC-OSSIFIED-SLEDGE', '“震荡”骨质战锤', '内置引力感应中枢的重型钝击武装。', '长度 1.6m，锤头体积巨大，整体质量高度集中。', '致密星兽颅骨残骸、微型神经中枢元件。', '依赖大幅度的物理挥动惯性。', '定向引力脉冲。内置神经中枢感应加速度，在撞击瞬间通过神髓能量定向释放重力震荡波，无视外装甲直接作用于内部组织。', NULL, NULL, NULL),
  ('NLA104-SAINTS-RIB-SCYTHE', '“圣徒肋骨”折叠大镰', '一种具备形态转换功能的机械冷兵器，可在重剑与大镰之间切换。', '折叠态 1.3m，展开态 2.2m。', '精锻黑铁、发条铰链结构、发条储能模块。', '需要手动转动侧面曲柄上弦（发条动力）。', '机械能转换。利用形态瞬间切换产生的离心力与惯性，通过复合刃口进行大范围切割或绕过防御钩取。', NULL, NULL, '符合该宇宙“肉体与铁器直接接触”的战斗教义。'),
  ('NLA104-INQUISITOR-PIERCER', '“审判官”螺旋刺枪', '高转速发条驱动的钻孔处决武器。', '全长 0.9m，呈锥形结构。', '高碳钢、活塞连杆系统、发条弹簧。', '高强度发条上弦；手动激发开关。', '机械钻孔与绞碎。三棱枪尖进行高转速旋转及往复活塞冲击，刺入后张开内部倒钩进行物理绞杀。', '{"rotation_speed": "800rpm", "piercing_force": "Grade-S"}'::jsonb, NULL, NULL),
  ('NLA104-EMBER-BLOOD-BLUNDERBUSS', '“余烬”短管散弹铳', '近距离大威力面杀伤火器。', '全长 0.5m，大口径扩口设计。', '铸铁枪管、干燥渊血结晶粉末、黑火药底火。', '黑火药初级推力；专用渊血晶体弹丸。', '动能冲击与化学致幻。利用爆燃推力发射碎片，弹药中混有的渊血粉末在热效应下释放高浓度致幻烟尘。', NULL, NULL, '有效射程限制在 10m 以内，以符合宇宙战术禁忌。'),
  ('NLA104-BOILING-BLOOD-NAILER', '“沸血”连发钉射器', '利用渊血相变产生的高压蒸汽驱动的长钉发射器。', '含底盘长度 0.7m，带顶部供弹匣。', '耐高压燃烧室、齿轮联动机构、金属长钉。', '持续燃烧的少量渊血；齿轮组需定期涂抹润滑油。', '蒸汽压动力。通过灼烧渊血产生的瞬时蒸汽压驱动活塞，将长钉自动压入并射出。', NULL, '武器外壳温度极高（常温 180℃ 以上），射手必须装备全隔热护手。', NULL),
  ('NLA104-THORN-SANGUINE-PUMP', '“荆棘”血泵拳刃', '一种与使用者循环系统直接连接的动力拳套。', '覆盖前臂至指尖的装甲结构。', '微型血泵、可伸缩合金倒刺、皮下穿刺针头。', '使用者的实时血液供应（高心率状态效能倍增）。', '生物压驱动。汲取使用者血液中的渊血能量，驱动拳面布满的倒刺进行极速往复伸缩，将打击力转化为撕裂力。', NULL, '存在失血过量风险；长期使用会导致血液中渊血浓度失衡引发精神污染。', NULL),
  ('NLA104-SLUMBERING-ICHOR-GRENADE', '“沉眠”圣水手雷', '利用化学反应产生毒性烟雾的投掷武器。', '标准玻璃容器体积（约 350ml）。', '高强度玻璃、净化液、腐蚀性渊血原液。', '碰撞破碎触发。', '剧烈放热反应。两种液体混合后迅速产生腐蚀性紫雾，具备溶解生物组织与麻痹神经系统的双重效果。', NULL, NULL, '作为该宇宙罕见的区域控制手段，其生效范围被限制在极小的战术半径内。')
  ) AS v(
    sku_code,
    armament_name,
    description,
    physical_dimensions,
    construction_feedstock,
    usage_dependency,
    operation_principle,
    extended_spec,
    defects_and_risks,
    design_constraints
  )
)
INSERT INTO public.weapon_armament_spec (
  weapon_id,
  armament_name,
  description,
  physical_dimensions,
  construction_feedstock,
  usage_dependency,
  operation_principle,
  extended_spec,
  defects_and_risks,
  design_constraints
)
SELECT
  w.id,
  s.armament_name,
  s.description,
  s.physical_dimensions,
  s.construction_feedstock,
  s.usage_dependency,
  s.operation_principle,
  s.extended_spec,
  s.defects_and_risks,
  s.design_constraints
FROM seed s
JOIN public.weapons w ON w.sku_code = s.sku_code
ON CONFLICT (weapon_id) DO UPDATE
SET
  armament_name = EXCLUDED.armament_name,
  description = EXCLUDED.description,
  physical_dimensions = EXCLUDED.physical_dimensions,
  construction_feedstock = EXCLUDED.construction_feedstock,
  usage_dependency = EXCLUDED.usage_dependency,
  operation_principle = EXCLUDED.operation_principle,
  extended_spec = EXCLUDED.extended_spec,
  defects_and_risks = EXCLUDED.defects_and_risks,
  design_constraints = EXCLUDED.design_constraints,
  updated_at = now();

WITH seed AS (
  SELECT *
  FROM (
    VALUES
  ('NLA89-DECAY-PULSE-CROSSBOW', '寂灭脉冲-星兽脊椎复合弩', '模拟星兽脊椎张力的远程动能武装，利用次声波震荡从分子层面瓦解目标生命。', '["星兽脊椎模拟生物张力结构", "神髓诱导次声波裂变伤害", "高张力干缩纤维驱动系统"]'::jsonb, '在寂静的以太洋流中，只有这一声脊椎弹响是敌人的葬礼。', 65000),
  ('NLA89-ECHOLIA-BOLTER', '回声-节律性括约肌连发髓枪', '紧凑型半自动生物手枪，通过痛觉中枢建立生物反馈，实现高频神髓结晶喷射。', '["痛觉感应中枢生物交互", "液压驱动节律性连发机构", "临界态神髓高压喷射流"]'::jsonb, '感受它的脉动，让痛觉成为你扣动扳机的唯一节拍。', 55000),
  ('NLA89-OSTEO-DISSOLVER-SPOUT', '溶骨者-背负式强酸喷雾系统', '阵地清场专家，利用合成浓缩胃酸瞬间溶解几丁质装甲与生物组织。', '["20L大容量生物培养囊肿", "多层几丁质可调喷射挡板", "极端化学氧化腐蚀效力"]'::jsonb, '无论是坚固的肋骨城邦还是厚重的甲壳，在“溶骨者”面前皆为流质。', 50000),
  ('NLA89-PREDATOR-CHAIN-SWORD', '捕食者-活性寄生虫振动链锯', '结合蚀骨虫寄生群体的近战利刃，万赫兹震荡配合生物啃噬，撕碎一切微观结构。', '["蚀骨虫群落高频振动切割", "神髓循环回路供能系统", "钙化剑刃基座生物强化"]'::jsonb, '它不只是武器，它是一个饥饿的猎手，渴望着下一片鲜肉。', 50000),
  ('NLA89-SEISMIC-OSSIFIED-SLEDGE', '震荡-定向引力脉冲重锤', '内置神经中枢感应加速度，在撞击瞬间释放重力震荡波，无视装甲摧毁内部组织。', '["致密星兽颅骨重型锤头", "内置神经中枢引力感应", "定向神髓重力震荡技术"]'::jsonb, '物理法则在这里低头，一锤定音，星骸颤栗。', 65000),
  ('NLA104-SAINTS-RIB-SCYTHE', '圣徒肋骨-发条折叠转换大镰', '符合暮血教义的机关冷兵器，可在重剑与大镰间瞬间切换，爆发极高离心力。', '["精锻黑铁发条铰链结构", "形态切换惯性增强系统", "多功能复核刃口设计"]'::jsonb, '祈祷吧，当齿轮咬合之声响起，救赎将以镰刃的形式降临。', 60000),
  ('NLA104-INQUISITOR-PIERCER', '审判官-高转速发条螺旋处决枪', '专门针对高价值目标的旋转处决武装，800rpm转速配合活塞冲击，物理性粉碎防御。', '["800RPM发条驱动钻头", "三棱往复活塞冲击机构", "刺入式自动张开绞杀钩"]'::jsonb, '每一个螺旋孔洞，都是对异端最彻底的审判。', 60000),
  ('NLA104-EMBER-BLOOD-BLUNDERBUSS', '余烬-渊血致幻短管散弹铳', '10米内无敌的杀戮机器，发射渊血结晶碎片，并在爆燃中释放高浓度致幻烟尘。', '["大口径铸铁扩口设计", "渊血粉末热效应致幻烟雾", "黑火药高动能面杀伤"]'::jsonb, '烟雾散尽后，他们将在疯狂与哀嚎中迎接终焉。', 50000),
  ('NLA104-BOILING-BLOOD-NAILER', '沸血-渊血蒸汽动力钉射器', '利用渊血相变产生的超高压蒸汽驱动，将金属长钉化作死神的连发箭矢。', '["渊血燃烧相变高压室", "精密齿轮联动连发机构", "180℃高温热能传导外壳"]'::jsonb, '感受这灼热的愤怒，蒸汽喷薄间，长钉已透骨。', 55000),
  ('NLA104-THORN-SANGUINE-PUMP', '荆棘-共生型动力血泵拳刃', '与使用者血液系统实时连接的苦修兵器，心率越高，撕裂频率越恐怖。', '["皮下穿刺式生物压驱动", "极速往复伸缩合金倒刺", "心率耦合动力倍增技术"]'::jsonb, '你的每一次心跳，都是敌人的皮开肉绽。', 55000),
  ('NLA104-SLUMBERING-ICHOR-GRENADE', '沉眠-渊血反应式腐蚀紫雾弹', '罕见的战术区域控制武装，碰撞后产生剧烈放热反应，释放高毒性溶解紫雾。', '["高强度玻璃双组份储存", "双液混合剧烈放热反应", "神经麻痹与组织溶解双效"]'::jsonb, '让这片紫色的迷雾，带他们进入永恒的沉眠。', 65000)
  ) AS v(
    sku_code,
    product_title,
    short_description,
    key_features,
    promo_copy,
    suggested_price_qc
  )
)
INSERT INTO public.weapon_merchandising (
  weapon_id,
  product_title,
  short_description,
  key_features,
  promo_copy,
  suggested_price_qc
)
SELECT
  w.id,
  s.product_title,
  s.short_description,
  s.key_features,
  s.promo_copy,
  s.suggested_price_qc
FROM seed s
JOIN public.weapons w ON w.sku_code = s.sku_code
ON CONFLICT (weapon_id) DO UPDATE
SET
  product_title = EXCLUDED.product_title,
  short_description = EXCLUDED.short_description,
  key_features = EXCLUDED.key_features,
  promo_copy = EXCLUDED.promo_copy,
  suggested_price_qc = EXCLUDED.suggested_price_qc,
  updated_at = now();

COMMIT;
